name: Deploy Code-Casting App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install and Build Frontend
        run: |
          cd code-cast-client
          npm install
          npm run build

      - name: Install Backend Dependencies
        run: |
          cd code-cast-server
          npm install

      - name: Archive Production Files
        run: |
          tar -czf deploy-package.tar.gz code-cast-client/.next code-cast-client/package.json code-cast-client/node_modules \
                                      code-cast-server/index.js code-cast-server/package.json code-cast-server/node_modules

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deploy-package
          path: deploy-package.tar.gz

  deploy:
    runs-on: self-hosted # Runs directly on your EC2 instance
    needs: build

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: deploy-package
          path: .

      - name: Extract Files
        run: |
          rm -rf code-cast-client
          rm -rf code-cast-server
          tar -xzf deploy-package.tar.gz -C /home/ubuntu/

      - name: Create .env Files
        run: |
          echo "NEXT_PUBLIC_BACKEND_URL=http://localhost:5000" > /home/ubuntu/code-cast-client/.env
          echo "PORT=5000" > /home/ubuntu/code-cast-server/.env
          echo "JODDLE_CLIENT_ID=867880fde36abf314e22980b8c644342" >> /home/ubuntu/code-cast-server/.env
          echo "JODDLE_CLIENT_SECRET=2008a722550be6caf2afeddfe3ccd5b4fac5c2abb5ee544cba187d9e59150b07" >> /home/ubuntu/code-cast-server/.env

      - name: Restart Backend with PM2
        run: |
          cd /home/ubuntu/code-cast-server
          pm2 stop backend || true
          pm2 start index.js --name backend

      - name: Restart Frontend with PM2
        run: |
          cd /home/ubuntu/code-cast-client
          pm2 stop client || true
          pm2 start "npm run start" --name client
